# Generated by Django 5.1.6 on 2025-04-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название конференции')),
                ('slug', models.SlugField(help_text="Уникальное имя для URL, например, 'tech-conf-2025'", max_length=200, unique=True, verbose_name='URL-имя (slug)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('organizers', models.TextField(help_text='Укажите организаторов через запятую', verbose_name='Организаторы')),
                ('format', models.CharField(help_text='Например: Офлайн, Онлайн, Гибридный', max_length=100, verbose_name='Формат проведения')),
                ('goal_image', models.ImageField(upload_to='conference_goals/', verbose_name='Изображение для цели конференции')),
                ('goal_text', models.TextField(verbose_name='Цель конференции')),
                ('plan', models.TextField(verbose_name='План проведения конференции')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(default='09:00', verbose_name='Время начала')),
                ('end_time', models.TimeField(default='12:00', verbose_name='Время окончания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(default='Не указан', max_length=100, verbose_name='Локация')),
                ('address', models.CharField(default='Не указан', max_length=200, verbose_name='Адрес')),
                ('location_details', models.CharField(default='Не указано', max_length=100, verbose_name='Уточнение локации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('image', models.ImageField(upload_to='news/', verbose_name='Изображение')),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название партнера')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('format', models.CharField(help_text='Например: Офлайн (адрес, аудитория) или Онлайн', max_length=100, verbose_name='Формат проведения')),
                ('online_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для онлайн-участия')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Мероприятие конференции',
                'verbose_name_plural': 'Мероприятия конференции',
            },
        ),
        migrations.CreateModel(
            name='ConferencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='conference_photos/', verbose_name='Фотография')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Фотография конференции',
                'verbose_name_plural': 'Фотографии конференции',
            },
        ),
        migrations.CreateModel(
            name='ConferenceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_file', models.FileField(upload_to='conference_videos/', verbose_name='Видео файл')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='events.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Видео конференции',
                'verbose_name_plural': 'Видео конференции',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя спикера')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('photo', models.ImageField(upload_to='speakers/', verbose_name='Фото спикера')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.conference', verbose_name='Конференция')),
            ],
            options={
                'verbose_name': 'Спикер',
                'verbose_name_plural': 'Спикеры',
            },
        ),
    ]
