# Generated by Django 5.1.6 on 2025-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='Не указан', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='12:00', verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
