# Generated by Django 5.1.6 on 2025-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_latitude_event_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location_details',
        ),
        migrations.AddField(
            model_name='event',
            name='goals',
            field=models.TextField(default='', verbose_name='Цели мероприятия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
    ]
